# Generated by Django 6.0.3 on 2026-03-10 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_locations', '0001_initial'),
        ('platform_accounts', '0001_initial'),
        ('platform_organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Membership that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership'),
        ),
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(help_text='Owning organization (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_organizations.organization'),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Membership that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['organization', 'created_at'], name='idx_location_org_created'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_location_org_code'),
        ),
    ]
