# Generated by Django 6.0.3 on 2026-03-10 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_locations', '0002_initial'),
        ('platform_accounts', '0002_tenantmember'),
        ('platform_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Unique code within the org, e.g. 'SE', 'PNW'.", max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['organization', 'name']},
        ),
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.JSONField(blank=True, default=dict, help_text='Capacity constraints: {max_daily_visits: N, max_teams: N, ...}'),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, default='US', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Operating hours: {"mon": {"start": "07:00", "end": "18:00"}, ...}'),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='service_area',
            field=models.JSONField(blank=True, default=dict, help_text='Service area config: {zips: [...], radius_miles: N, polygon: [...]}'),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text="IANA timezone, e.g. 'America/New_York'. Falls back to org default.", max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(help_text="Unique code within the org, e.g. 'ATL-001'.", max_length=50),
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Unique code within the org, e.g. 'ATL', 'PDX'.", max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Membership that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('organization', models.ForeignKey(help_text='Owning organization (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Membership that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
            ],
            options={
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='market',
            field=models.ForeignKey(blank=True, help_text='Parent market. Null allowed during migration from stub.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='crm_locations.market'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['organization', 'is_active'], name='idx_location_org_active'),
        ),
        migrations.AddField(
            model_name='region',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Membership that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership'),
        ),
        migrations.AddField(
            model_name='region',
            name='organization',
            field=models.ForeignKey(help_text='Owning organization (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_organizations.organization'),
        ),
        migrations.AddField(
            model_name='region',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Membership that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership'),
        ),
        migrations.AddField(
            model_name='market',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='crm_locations.region'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['organization', 'created_at'], name='idx_region_org_created'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_region_org_code'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['organization', 'created_at'], name='idx_market_org_created'),
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_market_org_code'),
        ),
    ]
