# Generated by Django 6.0.3 on 2026-03-11 23:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_accounts', '0003_membership_assigned_market_and_more'),
        ('platform_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, help_text='Membership that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('organization', models.ForeignKey(help_text='Owning organization (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Membership that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
            ],
            options={
                'ordering': ['service', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm_catalog.checklisttemplate')),
            ],
            options={
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Membership that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('organization', models.ForeignKey(help_text='Owning organization (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='crm_catalog.productcategory')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Membership that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, default='', help_text='Stock keeping unit, unique within the org. Auto-generated if blank.', max_length=64)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('item_type', models.CharField(choices=[('STOCK', 'Stock'), ('NON_STOCK', 'Non-Stock'), ('ADD_ON', 'Add-On'), ('BUNDLE', 'Bundle')], db_index=True, default='STOCK', max_length=20)),
                ('source_type', models.CharField(choices=[('PURCHASED', 'Purchased'), ('MANUFACTURED', 'Manufactured'), ('BOTH', 'Purchased and Manufactured')], default='PURCHASED', max_length=20)),
                ('tracking_type', models.CharField(choices=[('NONE', 'None'), ('QUANTITY', 'Quantity'), ('SERIAL', 'Serial')], default='NONE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_sellable', models.BooleanField(default=True)),
                ('is_purchasable', models.BooleanField(default=True)),
                ('is_consumable', models.BooleanField(default=False, help_text='Whether this product is consumed during service operations.')),
                ('default_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Internal cost per unit.', max_digits=12)),
                ('default_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Default sell price per unit.', max_digits=12)),
                ('reorder_enabled', models.BooleanField(default=False)),
                ('reorder_threshold', models.DecimalField(blank=True, decimal_places=4, help_text='Reorder when stock falls below this level.', max_digits=12, null=True)),
                ('reorder_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Suggested quantity to reorder.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('bundle_items', models.ManyToManyField(blank=True, help_text='Items included in this bundle (BUNDLE type only).', related_name='in_bundles', to='crm_catalog.product')),
                ('created_by', models.ForeignKey(blank=True, help_text='Membership that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('organization', models.ForeignKey(help_text='Owning organization (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Membership that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='crm_catalog.productcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_required', models.DecimalField(decimal_places=4, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_products', to='crm_catalog.product')),
                ('created_by', models.ForeignKey(blank=True, help_text='Membership that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('organization', models.ForeignKey(help_text='Owning organization (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_organizations.organization')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='crm_catalog.product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Membership that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
            ],
            options={
                'verbose_name': 'Product Component',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text="Unique service code within the org, e.g. 'SVC-STD-CLEAN'.", max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('base_duration_minutes', models.PositiveIntegerField(default=0, help_text='Estimated time to complete (minutes).')),
                ('skill_tags', models.JSONField(blank=True, default=list, help_text='Skill tags for crew matching, e.g. ["carpet", "hardwood"].')),
                ('default_recurrence', models.CharField(choices=[('ONE_TIME', 'One-time'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('CUSTOM', 'Custom')], default='ONE_TIME', max_length=20)),
                ('recurrence_options', models.JSONField(blank=True, default=dict, help_text='Allowed recurrence types with pricing multipliers: {"weekly": 1.0, "biweekly": 1.05}.')),
                ('base_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base hourly or per-unit rate.', max_digits=10)),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat base fee added to rate calculation.', max_digits=10)),
                ('min_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum charge regardless of calculation.', max_digits=10)),
                ('travel_surcharge', models.BooleanField(default=False, help_text='Whether travel surcharge applies.')),
                ('notes', models.TextField(blank=True, default='')),
                ('allowed_addons', models.ManyToManyField(blank=True, help_text='Other services that can be added on to this one.', related_name='addon_for_services', to='crm_catalog.service')),
                ('created_by', models.ForeignKey(blank=True, help_text='Membership that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('organization', models.ForeignKey(help_text='Owning organization (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_organizations.organization')),
                ('required_products', models.ManyToManyField(blank=True, help_text='Products consumed or required when performing this service.', related_name='used_in_services', to='crm_catalog.product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Membership that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='crm_catalog.service'),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Membership that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('organization', models.ForeignKey(help_text='Owning organization (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='crm_catalog.servicecategory')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Membership that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='crm_catalog.servicecategory'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', help_text='Optional internal supplier code.', max_length=50)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.URLField(blank=True, default='')),
                ('payment_terms', models.CharField(blank=True, default='', help_text='e.g. Net-30, Net-60, COD.', max_length=100)),
                ('account_number', models.CharField(blank=True, default='', max_length=100)),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=120)),
                ('postal_code', models.CharField(blank=True, default='', max_length=30)),
                ('country', models.CharField(blank=True, default='US', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, help_text='Membership that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('organization', models.ForeignKey(help_text='Owning organization (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Membership that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplierLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_sku', models.CharField(blank=True, default='', max_length=64)),
                ('supplier_product_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_preferred', models.BooleanField(default=False, help_text='Preferred supplier for this product.')),
                ('last_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_order_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, help_text='Membership that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('organization', models.ForeignKey(help_text='Owning organization (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='crm_catalog.product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Membership that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_links', to='crm_catalog.supplier')),
            ],
            options={
                'verbose_name': 'Product–Supplier Link',
                'ordering': ['product__name', 'supplier__name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='products', through='crm_catalog.ProductSupplierLink', to='crm_catalog.supplier'),
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name, e.g. Each, Box, Gallon, Hour.', max_length=50)),
                ('code', models.CharField(help_text='Short code, e.g. EA, BOX, GAL, HR.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_fractional', models.BooleanField(default=False, help_text='Whether this unit allows decimal quantities.')),
                ('precision', models.PositiveSmallIntegerField(default=0, help_text='Decimal places allowed when is_fractional=True.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Membership that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('organization', models.ForeignKey(help_text='Owning organization (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Membership that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, help_text='Pricing unit, e.g. per hour, per sqft.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='crm_catalog.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, help_text='How this product is measured/priced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='crm_catalog.unitofmeasure'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(help_text='Unique within the org.', max_length=64)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('tracking_type', models.CharField(choices=[('NONE', 'None'), ('QUANTITY', 'Quantity'), ('SERIAL', 'Serial')], default='QUANTITY', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_purchasable', models.BooleanField(default=True)),
                ('is_consumable', models.BooleanField(default=True)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, help_text='Membership that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('organization', models.ForeignKey(help_text='Owning organization (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Membership that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='crm_catalog.unitofmeasure')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uq_prodcat_org_name'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uq_prodcat_org_slug'),
        ),
        migrations.AddConstraint(
            model_name='productcomponent',
            constraint=models.UniqueConstraint(fields=('organization', 'parent_product', 'component_product'), name='uq_prodcomp_org_parent_comp'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(fields=('service', 'version'), name='uq_checklist_svc_version'),
        ),
        migrations.AddConstraint(
            model_name='servicecategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uq_svccat_org_name'),
        ),
        migrations.AddConstraint(
            model_name='servicecategory',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uq_svccat_org_slug'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['organization', 'is_active'], name='idx_supplier_org_active'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uq_supplier_org_name'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('organization', 'code'), name='uq_supplier_org_code_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='productsupplierlink',
            constraint=models.UniqueConstraint(fields=('organization', 'product', 'supplier'), name='uq_prodsuplink_org_prod_sup'),
        ),
        migrations.AddConstraint(
            model_name='productsupplierlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_preferred', True)), fields=('organization', 'product'), name='uq_prodsuplink_one_preferred'),
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['organization', 'is_active'], name='idx_uom_org_active'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_uom_org_code'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uq_uom_org_name'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['organization', 'status'], name='idx_service_org_status'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['organization', 'created_at'], name='idx_service_org_created'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_service_org_code'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'status'], name='idx_product_org_status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'item_type'], name='idx_product_org_itemtype'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'created_at'], name='idx_product_org_created'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('organization', 'sku'), name='uq_product_org_sku_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('organization', 'barcode'), name='uq_product_org_barcode_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('default_cost__gte', 0)), name='ck_product_cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('default_price__gte', 0)), name='ck_product_price_gte_0'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['organization', 'status'], name='idx_material_org_status'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('organization', 'sku'), name='uq_material_org_sku'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('organization', 'barcode'), name='uq_material_org_barcode_nonblank'),
        ),
    ]
