# Generated by Django 6.0.3 on 2026-03-11 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_accounts', '0003_membership_assigned_market_and_more'),
        ('platform_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Unique code within the org, e.g. 'SVC-STD-CLEAN', 'AO-INT-WIN'.", max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('item_type', models.CharField(choices=[('SERVICE', 'Service'), ('ADD_ON', 'Add-on'), ('PRODUCT', 'Product'), ('BUNDLE', 'Bundle')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('base_duration_minutes', models.PositiveIntegerField(default=0, help_text='Estimated time to complete this service (minutes). 0 for products.')),
                ('skill_tags', models.JSONField(blank=True, default=list, help_text='Skill tags for crew matching, e.g. ["carpet", "hardwood", "commercial"].')),
                ('default_recurrence', models.CharField(blank=True, choices=[('ONE_TIME', 'One-time'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='ONE_TIME', help_text='Default recurrence for this service when creating visit plans.', max_length=20)),
                ('recurrence_options', models.JSONField(blank=True, default=dict, help_text='Allowed recurrence types with pricing factor multipliers. e.g. {"weekly": 1.0, "biweekly": 1.05, "monthly": 1.15}')),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, help_text='Base hourly or per-unit rate.', max_digits=10)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, help_text='Flat base fee (added to rate-based calculation).', max_digits=10)),
                ('min_charge', models.DecimalField(decimal_places=2, default=0, help_text='Minimum charge regardless of calculation.', max_digits=10)),
                ('travel_surcharge', models.BooleanField(default=False, help_text='Whether travel surcharge applies to this item.')),
                ('allowed_addons', models.ManyToManyField(blank=True, help_text='Add-on items that can be attached to this service/bundle.', limit_choices_to={'item_type': 'ADD_ON'}, related_name='addon_for_items', to='crm_catalog.catalogitem')),
                ('bundle_items', models.ManyToManyField(blank=True, help_text='Items included in this bundle (only relevant for BUNDLE type).', related_name='in_bundles', to='crm_catalog.catalogitem')),
                ('created_by', models.ForeignKey(blank=True, help_text='Membership that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('organization', models.ForeignKey(help_text='Owning organization (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Membership that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
            ],
            options={
                'ordering': ['organization', 'item_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Template name, e.g. 'Standard Cleaning Checklist'.", max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number. Increment when modifying an active template.')),
                ('catalog_item', models.ForeignKey(help_text='The service or bundle this checklist applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='crm_catalog.catalogitem')),
                ('created_by', models.ForeignKey(blank=True, help_text='Membership that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('organization', models.ForeignKey(help_text='Owning organization (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Membership that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
            ],
            options={
                'ordering': ['catalog_item', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the checklist.')),
                ('description', models.CharField(help_text="Step description, e.g. 'Vacuum all carpeted areas'.", max_length=500)),
                ('is_required', models.BooleanField(default=True, help_text='If true, this step must be completed for the checklist to pass.')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm_catalog.checklisttemplate')),
            ],
            options={
                'ordering': ['template', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['organization', 'item_type'], name='idx_catalogitem_org_type'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['organization', 'is_active'], name='idx_catalogitem_org_active'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['organization', 'created_at'], name='idx_catalogitem_org_created'),
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_catalogitem_org_code'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(fields=('catalog_item', 'version'), name='uq_checklist_template_item_version'),
        ),
    ]
