# Generated by Django 6.0.3 on 2026-03-10 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_accounts', '0002_tenantmember'),
        ('platform_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_type', models.CharField(choices=[('LOCATIONS', 'Location Hierarchy'), ('CATALOG', 'Catalog Items'), ('ROLES', 'Roles'), ('OTHER', 'Other')], max_length=30)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DRY_RUN', 'Dry Run Complete'), ('COMMITTED', 'Committed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('is_dry_run', models.BooleanField(default=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors_json', models.JSONField(blank=True, default=list, help_text='List of {line, code, error} dicts.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_runs', to='platform_organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'import_type', 'created_at'], name='idx_importrun_org_type_date')],
            },
        ),
    ]
