# Generated by Django 6.0.3 on 2026-03-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier. Used as subdomain for tenant resolution.', max_length=63, unique=True)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], db_index=True, default='TRIAL', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Tenant-level configuration (timezone, defaults, feature flags, etc.).')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='idx_org_slug'), models.Index(fields=['status'], name='idx_org_status')],
            },
        ),
    ]
