# Generated by Django 6.0.3 on 2026-03-10 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_accounts', '0002_tenantmember'),
        ('platform_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, default='', help_text='Denormalized actor email for readability when membership is deleted.', max_length=254)),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('DATA', 'Data change'), ('IMPORT', 'Import operation'), ('WORKFLOW', 'Workflow transition'), ('OVERRIDE', 'Override / exception'), ('SYSTEM', 'System event')], db_index=True, default='DATA', max_length=20)),
                ('event_type', models.CharField(db_index=True, help_text="Specific event code, e.g. 'lead.created', 'quote.converted', 'pricing.override', 'import.started'.", max_length=100)),
                ('entity_type', models.CharField(blank=True, db_index=True, default='', help_text="Model name of the affected entity, e.g. 'Lead', 'Quote', 'Role'.", max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', help_text='Primary key of the affected entity.', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured data: diff payload, inputs, outputs, context.')),
                ('reason', models.TextField(blank=True, default='', help_text='Required for sensitive actions (overrides, reassignments, deletions). Free-text explanation of why the action was taken.')),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', help_text='Request correlation ID for tracing.', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address from the request.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Client User-Agent header.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_membership', models.ForeignKey(blank=True, help_text='Membership that performed the action. Null for system events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_accounts.membership')),
                ('organization', models.ForeignKey(blank=True, help_text='Owning organization. Null for global/platform events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_organizations.organization')),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='idx_audit_org_created'), models.Index(fields=['organization', 'event_type'], name='idx_audit_org_event_type'), models.Index(fields=['entity_type', 'entity_id'], name='idx_audit_entity'), models.Index(fields=['correlation_id'], name='idx_audit_correlation')],
            },
        ),
    ]
