# Generated by Django 6.0.3 on 2026-03-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMember',
            fields=[
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('platform_accounts.membership',),
        ),
    ]
