# Generated by Django 6.0.3 on 2026-03-10 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_locations', '0003_region_alter_location_options_location_capacity_and_more'),
        ('platform_accounts', '0002_tenantmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='assigned_market',
            field=models.ForeignKey(blank=True, help_text='Primary market assignment for this member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm_locations.market'),
        ),
        migrations.AddField(
            model_name='membership',
            name='assigned_region',
            field=models.ForeignKey(blank=True, help_text='Primary region assignment for this member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm_locations.region'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='default_location',
            field=models.ForeignKey(blank=True, help_text='Primary location assignment for this member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm_locations.location'),
        ),
    ]
