# Generated by Django 6.0.3 on 2026-03-10 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_accounts', '0001_initial'),
        ('platform_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Stable dotted code, e.g. 'leads.convert', 'pricing.preview'.", max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Human-readable description of what this capability allows.', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive capabilities are hidden from role assignment UI.')),
            ],
            options={
                'verbose_name_plural': 'capabilities',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Machine-readable code, unique within the org. Used for imports.', max_length=100)),
                ('name', models.CharField(help_text='Human-readable display name.', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Optional longer description of this role's purpose.")),
                ('is_system', models.BooleanField(default=False, help_text='System roles are created by the platform and cannot be deleted by org admins.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='platform_organizations.organization')),
            ],
            options={
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_capabilities', to='platform_rbac.capability')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_capabilities', to='platform_rbac.role')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='capabilities',
            field=models.ManyToManyField(blank=True, related_name='roles', through='platform_rbac.RoleCapability', to='platform_rbac.capability'),
        ),
        migrations.CreateModel(
            name='ScopeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to', models.CharField(default='*', help_text="Domain this scope applies to. '*' = all domains. Future: 'leads', 'quotes', 'visits', etc.", max_length=100)),
                ('scope_level', models.CharField(choices=[('ALL_ORG', 'All records in the organization'), ('SELF_ASSIGNED', 'Only records assigned to me')], default='ALL_ORG', max_length=30)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_rules', to='platform_rbac.role')),
            ],
            options={
                'ordering': ['role', 'applies_to'],
            },
        ),
        migrations.CreateModel(
            name='MembershipRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_roles', to='platform_accounts.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_roles', to='platform_rbac.role')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('membership', 'role'), name='uq_membership_role')],
            },
        ),
        migrations.AddConstraint(
            model_name='rolecapability',
            constraint=models.UniqueConstraint(fields=('role', 'capability'), name='uq_role_capability'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'is_active'], name='idx_role_org_active'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_role_org_code'),
        ),
        migrations.AddConstraint(
            model_name='scoperule',
            constraint=models.UniqueConstraint(fields=('role', 'applies_to'), name='uq_scope_rule_role_domain'),
        ),
    ]
