# Generated by Django 6.0.3 on 2026-03-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoperule',
            name='scope_level',
            field=models.CharField(choices=[('ALL_ORG', 'All records in the organization'), ('REGION', 'Records in assigned region'), ('MARKET', 'Records in assigned market'), ('LOCATION', 'Records in assigned location'), ('SELF_ASSIGNED', 'Only records assigned to me')], default='ALL_ORG', max_length=30),
        ),
    ]
